options:
  env:
    - KUBECONFIG=/tmp/kubeconfig
  machineType: E2_HIGHCPU_8

timeout: 1200s
tags: ['k8-test', '$TAG_NAME', '$SHORT_SHA']

substitutions:
  _APP_NAME: k8-test
  _TAG: '${BRANCH_NAME}-${SHORT_SHA}'
  _MLS_TYPE: TEST
  _MLS_TYPES: ""
  _PORT: '8080'

steps:
  - id: build-image
    name: gcr.io/kaniko-project/executor
    args:
      - --destination=gcr.io/$PROJECT_ID/$_APP_NAME:$_TAG
      - --cache=true
  - id: deploy-test
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=./output/test
      - --cluster=${_GKE_CLUSTER}
      - --location=${_GKE_REGION}
      - --output=gke-output/test
      - --timeout=10m0s
    waitFor: [build-image]
  - id: deploy-aar
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=./output/aar
      - --cluster=${_GKE_CLUSTER}
      - --location=${_GKE_REGION}
      - --output=gke-output/aar
      - --timeout=10m0s
    waitFor: [build-image]
  - id: deploy-ingress
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=./gcp/ingress
      - --cluster=${_GKE_CLUSTER}
      - --location=${_GKE_REGION}
      - --namespace=${_NAMESPACE}
      - --output=gke-output/test-ingress
      - --timeout=10m0s
    waitFor: [build-image]