options:
  env:
    - KUBECONFIG=/tmp/kubeconfig
  machineType: E2_HIGHCPU_8

timeout: 1200s
tags: ['test']

steps:
  - id: deploy
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=./gcp/main
      - --cluster=${_GKE_CLUSTER}
      - --location=${_GKE_REGION}
      - --namespace=${_NAMESPACE}
      - --output=gke-output/test
      - --timeout=10m0s
  - id: deploy-ingress
    name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=./gcp/ingress
      - --cluster=${_GKE_CLUSTER}
      - --location=${_GKE_REGION}
      - --namespace=${_NAMESPACE}
      - --output=gke-output/test-ingress
      - --timeout=10m0s