apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-test-{{ lower .Values.mlsType }}
spec:
  selector:
    matchLabels:
      greeting: hello
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        greeting: hello
        version: one
    spec:
      containers:
      - name: k8-test-{{ lower .Values.mlsType }}
        image: "gcr.io/{{ .Values.gcpProjectId }}/{{ .Values.imageName}}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        env:
        - name: "PORT"
          value: "8081"
        - name: "MLS_TYPE"
          value: {{ .Values.mlsType }}