apiVersion: v1
kind: Service
metadata:
  name: k8-test-{{ lower .Values.mlsType }}
spec:
  type: NodePort
  selector:
    greeting: hello
    version: one
  ports:
  - protocol: TCP
    port: {{ .Values.port}}
    targetPort: 8081